name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-backend-lib-generic.yml@c9a05e3d86f2a7d3e459d40667262f96753ecf5d
    with:
      sonarOrganization: gridsuite
      sonarProjectKey: org.gridsuite:filter
      eventType: filter_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
