name: Release

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type increment (major | minor)'
        required: true
        type: choice
        options:
          - major
          - minor

jobs:
  run-release:
    uses: powsybl/github-ci/.github/workflows/release-backend-lib-generic.yml@c9a05e3d86f2a7d3e459d40667262f96753ecf5d
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      versionType: ${{ github.event.inputs.versionType }}
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
