filter.evaluation.listFilter.allFound=Applying list filter of ${searchCount} elements (type ${equipementType}) : all elements found
filter.evaluation.listFilter.notFound=Applying list filter of ${searchCount} elements (type ${equipementType}) : ${notFoundCount} elements not found (${notFoundIds})
