filter.evaluation.general.countMatchingEquipments=${count} matching equipments found in the network
filter.evaluation.general.noMatchingEquipment=No matching equipment found in the network
filter.evaluation.listFilter.evaluate=Evaluate identifier list filter of ${searchCount} elements (type ${equipmentType})
filter.evaluation.listFilter.notFound=Partial match: ${notFoundCount} elements not found
filter.evaluation.listFilter.notFoundId=${id} not found
